[package]
name = "sqlx_table_binding"
version = "0.1.0"
authors = ["Bryn Coldwell"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
sqlx = { version = "0.3.5", default-features = false, features = [ "runtime-tokio", "macros", "postgres" ] }
tokio = { version = "0.2", features = ["full"] }
