version: "3.8"
services:
  postgres:
    image: postgres:12
    volumes:
      - ./files/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
